[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "alfresco"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-alfresco"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
